config/routes.rb
Rails.application.routes.draw do
  root to: "passengers#index"
  
  resources :passengers do
    resources :suitcases
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base

  has_many :suitcases

end

app/models/suitcase.rb
class Suitcase < ActiveRecord::Base

  belongs_to :passenger

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  def index
    @passengers = Passenger.all
  end

end

app/controllers/suitcases_controller.rb
class SuitcasesController < ApplicationController

  before_action do
    @passenger = Passenger.find(params[:passenger_id])
  end

  def index
    @suitcases = @passenger.suitcases
  end

  def show
    @suitcase = @passenger.suitcases.find(params[:id])
  end

  def new
    @suitcase = @passenger.suitcases.new
  end

  def create
    @suitcase = @passenger.suitcases.new(suitcase_params)
    if @suitcase.save
      redirect_to passenger_suitcase_path(@passenger, @suitcase)
    else
      render :new
    end
  end

  def edit
    @suitcase = @passenger.suitcases.find(params[:id])
  end

  def update
    @suitcase = @passenger.suitcases.find(params[:id])
    if @suitcase.update(suitcase_params)
      redirect_to passenger_suitcase_path(@passenger, @suitcase)
    else
      render :edit
    end
  end

  def destroy
    @suitcase = @passenger.suitcases.find(params[:id])
    @suitcase.destroy
    redirect_to suitcases_path
  end

  private

  def suitcase_params
    params.require(:suitcase).permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>gSchool Nested Resources Exercise</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">gSchool</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Passengers", passengers_path %></li>
            
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/passengers/index.html.erb
<div class="page-header">
  <h1>Passengers</h1>
</div>

<% if @passengers.present? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @passengers.each do |passenger| %>
        <tr>
          <td><%= passenger.name %></td>
          <td>
            <%= link_to "Passenger suitcases", passenger_suitcases_path(passenger) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="jumbotron">
    <h1>You forgot to run <code>rake db:seed</code></h1>
  </div>
<% end %>

app/views/suitcases/_form.html.erb
<%= form_for [@passenger, @suitcase] do |f| %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/suitcases/edit.html.erb
<div class="page-header">
  <h1>Edit Suitcase</h1>
</div>

<%= render "form" %>

app/views/suitcases/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New Suitcase", new_passenger_suitcase_path(@passenger), class: "btn btn-info" %>
  </div>
  <h1>Suitcases</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @suitcases.each do |suitcase| %>
      <tr>
        <td><%= link_to suitcase.description, passenger_suitcase_path(@passenger, suitcase) %></td>
        <td>
          <div class="pull-right">
            <%= link_to "edit", edit_passenger_suitcase_path(@passenger, suitcase) %>
            |
            <%= link_to "delete", passenger_suitcase_path(@passenger, suitcase, method: :delete, data: {confirm: "Are you sure?"}) %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/suitcases/new.html.erb
<div class="page-header">
  <h1>New Suitcase</h1>
</div>

<%= render "form" %>

app/views/suitcases/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Edit", edit_passenger_suitcase_path(@passenger, @suitcase), class: "btn btn-info" %>
  </div>
  <h1>Show Suitcase</h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Suitcases", passenger_suitcases_path(@passenger) %></li>
  <li class="active">Show</li>
</ol>

<%= @suitcase.description %>